name: CI

on:
  push:
    branches:
      - dev
      - prod
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      ALLOWED_HOSTS: '["*"]'
      DB__NAME: pushup_api_test
      SECRET_KEY: kKVm&hmMW!G2ouY

    services:
      database:
        image: postgres:alpine
        env:
          POSTGRES_DB: pushup_api_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432

      stripe-mock:
        image: stripe/stripe-mock
        ports:
          - 12111:12111

    steps:
      - name: Run checkout
        uses: actions/checkout@v5

      - name: Set up environment
        uses: ./.github/actions/environment

      - name: Check code style
        uses: ./.github/actions/code-style

      - name: Compile messages
        uses: ./.github/actions/compile-messages

      - name: Apply migrations
        uses: ./.github/actions/apply-migrations

      - name: Check migrations
        uses: ./.github/actions/check-migrations

      - name: Tests
        uses: ./.github/actions/tests
